[pytest]
# Enable live logging to the console
log_cli = true
# Set the logging level to INFO
log_cli_level = INFO
# Customize the log format to include timestamp, log level, message, filename, and line number
log_cli_format = %(asctime)s - %(levelname)s - %(message)s (%(filename)s:%(lineno)s)
# Set the date format to include the date and time in UTC
log_cli_date_format = %Y-%m-%d %H:%M:%SZ

markers =
    positive
    negative
